<?php

$category = $block->getCategory();
$collection = $block->getCategoryCollection();
$level = $category->getLevel();
$ajaxsearchHelper = $this->helper(\Swissup\Ajaxsearch\Helper\Data::class);
if (!$ajaxsearchHelper->isCategoryFilterEnabled()) {
    return;
}
$categoryVarName = $ajaxsearchHelper->getCategoryVarName();
?>
<select name="<?= $block->escapeHtmlAttr($categoryVarName) ?>" id="swissup-ajaxsearch-filter-category" data-placeholder="<?= $block->escapeHtmlAttr(__('All')) ?>">
    <option value="0"><?= $block->escapeHtml(__('All')) ?></option>
    <?php if ($category->isInRootCategoryList()) :?>
        <?php $parentCategory = $category->getParentCategory();
        if ($parentCategory->isInRootCategoryList()) :
            $level = $parentCategory->getLevel();
            $name = $block->getOptionName($parentCategory, $level/*, '&lt;'*/);
        ?>
            <option value="<?= $block->escapeHtmlAttr($parentCategory->getId()) ?>"><?= $block->escapeHtml($name) ?></option>
        <?php endif;
            $name = $block->getOptionName($category, $level/*, '|'*/);
        ?>
        <option value="<?= $block->escapeHtmlAttr($category->getId()) ?>"><?= $block->escapeHtml($name) ?></option>
    <?php endif;
    if ($collection->getSize()) :
        foreach ($collection as $_category) :
            $name = $block->getOptionName($_category, $level);
    ?>
            <option value="<?= $block->escapeHtmlAttr($_category->getId()) ?>"><?= $block->escapeHtml($name) ?></option>
        <?php endforeach; ?>
    <?php endif ?>
</select>