<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<span class="product-image-container"
      style="width:<?= $block->escapeHtmlAttr($block->getWidth())?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= ($block->getRatio() * 100); ?>%;">
        <img class="product-image-photo"
             <?= $block->escapeHtml($block->getCustomAttributes()); ?>
             src="<?= $block->escapeUrl($block->getImageUrl()); ?>"
             width="<?= $block->escapeHtmlAttr($block->getResizedImageWidth()); ?>"
             height="<?= $block->escapeHtmlAttr($block->getResizedImageHeight()); ?>"
             alt="<?= $block->escapeHtmlAttr($block->stripTags($block->getLabel(), null, true)); ?>"/>
    </span>
</span>